In [2]:
l1 = [10, 20, 30, 40]

In [4]:
l1[1:3] = [1, 2]

In [5]:
l1

[10, 1, 2, 40]

### numpy

In [6]:
import numpy as np

In [12]:
l1 = [1, 2, 3, 4, 5]

In [13]:
np.array(l1)

array([1, 2, 3, 4, 5])

In [17]:
np.array( [[l1, l1], [l1, l1]] )

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [8]:
np.zeros( 5 )

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros( (3, 5) )

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.zeros( (2, 3, 5) )

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros( (2, 3, 5) )

In [20]:
np.ones((5, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.full( (5, 3), 'Python' )

array([['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python'],
       ['Python', 'Python', 'Python']], dtype='<U6')

In [27]:
np.array( range(1, 11, 1) )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(0, 1.01, 0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [39]:
np.linspace( 1, 10, 20 )

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [89]:
np.random.random( 100 )

array([0.78134266, 0.63396289, 0.28747652, 0.35497664, 0.99661045,
       0.35530808, 0.1970634 , 0.87124929, 0.64332994, 0.53420286,
       0.0568513 , 0.29457154, 0.99304064, 0.92851846, 0.78287488,
       0.49113396, 0.94604331, 0.7121273 , 0.38797405, 0.27981274,
       0.23051544, 0.63990011, 0.0111621 , 0.1319011 , 0.71385475,
       0.05319777, 0.26141372, 0.62939012, 0.91480882, 0.85705028,
       0.41138391, 0.99061443, 0.22709164, 0.37750209, 0.8258484 ,
       0.72462609, 0.38187916, 0.81229792, 0.49678387, 0.23079828,
       0.17154273, 0.98903115, 0.42475379, 0.86317665, 0.10003547,
       0.54326907, 0.80184082, 0.97409632, 0.96899036, 0.16681012,
       0.49382015, 0.99988175, 0.4958474 , 0.75194922, 0.63873566,
       0.76294977, 0.10284591, 0.73378289, 0.65792753, 0.47159261,
       0.77120782, 0.47498102, 0.46709696, 0.32463222, 0.13999498,
       0.98403665, 0.4583333 , 0.42842877, 0.09956654, 0.16938027,
       0.31829809, 0.81348009, 0.63317819, 0.88362674, 0.62551

In [107]:
# get 15 two digit random numbers
np.random.randint( 10, 100, 15 )

array([96, 77, 95, 41, 68, 49, 59, 76, 23, 44, 97, 47, 10, 79, 60])

In [125]:
# get 20 three digit random numbers in the shape 4, 5
a1 = np.random.randint(100, 1000, 20)

In [126]:
a1.ndim

1

In [127]:
a1.shape

(20,)

In [128]:
a1

array([378, 480, 595, 777, 489, 490, 619, 908, 188, 545, 998, 675, 289,
       465, 201, 285, 932, 435, 248, 250])

In [129]:
a1.size

20

In [130]:
a1.reshape((4, 5))

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675, 289, 465, 201],
       [285, 932, 435, 248, 250]])

In [131]:
a1.reshape((3, 5))

ValueError: cannot reshape array of size 20 into shape (3,5)

In [132]:
a2 = a1.reshape((4, 5))

In [133]:
a2.ndim

2

In [134]:
a2.shape

(4, 5)

In [135]:
a2.size

20

In [136]:
a2

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675, 289, 465, 201],
       [285, 932, 435, 248, 250]])

In [137]:
a2.reshape((2, 2, 5))

array([[[378, 480, 595, 777, 489],
        [490, 619, 908, 188, 545]],

       [[998, 675, 289, 465, 201],
        [285, 932, 435, 248, 250]]])

In [138]:
a2.reshape((20))

array([378, 480, 595, 777, 489, 490, 619, 908, 188, 545, 998, 675, 289,
       465, 201, 285, 932, 435, 248, 250])

In [139]:
a2

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675, 289, 465, 201],
       [285, 932, 435, 248, 250]])

In [140]:
a2.shape

(4, 5)

In [141]:
a2.T

array([[378, 490, 998, 285],
       [480, 619, 675, 932],
       [595, 908, 289, 435],
       [777, 188, 465, 248],
       [489, 545, 201, 250]])

In [142]:
a2.transpose()

array([[378, 490, 998, 285],
       [480, 619, 675, 932],
       [595, 908, 289, 435],
       [777, 188, 465, 248],
       [489, 545, 201, 250]])

In [143]:
type(a2)

numpy.ndarray

##### access the data the from ndarray

In [147]:
a1

array([378, 480, 595, 777, 489, 490, 619, 908, 188, 545, 998, 675, 289,
       465, 201, 285, 932, 435, 248, 250])

In [149]:
a1[0]

378

In [150]:
a1[-1]

250

In [151]:
a1[:3]

array([378, 480, 595])

In [152]:
a1[3:7]

array([777, 489, 490, 619])

In [153]:
a1[::2]

array([378, 595, 489, 619, 188, 998, 289, 201, 932, 248])

In [154]:
a1[1::2]

array([480, 777, 490, 908, 545, 675, 465, 285, 435, 250])

In [155]:
a2

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675, 289, 465, 201],
       [285, 932, 435, 248, 250]])

In [156]:
a2[1, 4]

545

In [157]:
a2[::,::]

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675, 289, 465, 201],
       [285, 932, 435, 248, 250]])

In [158]:
a2[0,::]

array([378, 480, 595, 777, 489])

In [159]:
a2[0]

array([378, 480, 595, 777, 489])

In [160]:
a2[-1]

array([285, 932, 435, 248, 250])

In [162]:
a2[:2,]

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545]])

In [163]:
a2

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675, 289, 465, 201],
       [285, 932, 435, 248, 250]])

In [164]:
a2[, 0]

SyntaxError: invalid syntax (<ipython-input-164-a8c2409d5ed4>, line 1)

In [165]:
a2[:, 0]

array([378, 490, 998, 285])

In [166]:
a2[:, -1]

array([489, 545, 201, 250])

In [167]:
a2[:2, :3]

array([[378, 480, 595],
       [490, 619, 908]])

In [168]:
a2

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675, 289, 465, 201],
       [285, 932, 435, 248, 250]])

In [169]:
a2[2, 2:4]

array([289, 465])

In [170]:
a2[:3, 2:]

array([[595, 777, 489],
       [908, 188, 545],
       [289, 465, 201]])

In [171]:
a2[1:3, :3]

array([[490, 619, 908],
       [998, 675, 289]])

In [172]:
a2[1, 2]

908

In [175]:
a1

array([378, 480, 595, 777, 489, 490, 619, 908, 188, 545, 998, 675, 289,
       465, 201, 285, 932, 435, 248, 250])

In [176]:
a1[1]

480

In [177]:
a1[1:2]

array([480])

In [173]:
a2

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675, 289, 465, 201],
       [285, 932, 435, 248, 250]])

In [174]:
a2[1, 2]

908

In [178]:
a2[1:2, 2:3]

array([[908]])

In [179]:
a2[1, 2:3]

array([908])

In [180]:
a2[1:2, 2]

array([908])

In [181]:
a2

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675, 289, 465, 201],
       [285, 932, 435, 248, 250]])

In [183]:
a2[2, 2] = 0

In [184]:
a2

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675,   0, 465, 201],
       [285, 932, 435, 248, 250]])

In [186]:
a2[2:, 3:] = -1

In [187]:
a2

array([[378, 480, 595, 777, 489],
       [490, 619, 908, 188, 545],
       [998, 675,   0,  -1,  -1],
       [285, 932, 435,  -1,  -1]])

In [189]:
a2[0, 3:] = [-1, -2]

In [190]:
a2

array([[378, 480, 595,  -1,  -2],
       [490, 619, 908, 188, 545],
       [998, 675,   0,  -1,  -1],
       [285, 932, 435,  -1,  -1]])

In [192]:
a2 + 10

array([[ 388,  490,  605,    9,    8],
       [ 500,  629,  918,  198,  555],
       [1008,  685,   10,    9,    9],
       [ 295,  942,  445,    9,    9]])

In [194]:
a2 / 10

array([[37.8, 48. , 59.5, -0.1, -0.2],
       [49. , 61.9, 90.8, 18.8, 54.5],
       [99.8, 67.5,  0. , -0.1, -0.1],
       [28.5, 93.2, 43.5, -0.1, -0.1]])

In [195]:
a2 

array([[378, 480, 595,  -1,  -2],
       [490, 619, 908, 188, 545],
       [998, 675,   0,  -1,  -1],
       [285, 932, 435,  -1,  -1]])

In [196]:
a2 % 2 == 0

array([[ True,  True, False, False,  True],
       [ True, False,  True,  True, False],
       [ True, False,  True, False, False],
       [False,  True, False, False, False]])

In [198]:
a2[ a2 % 2 != 0 ]

array([595,  -1, 619, 545, 675,  -1,  -1, 285, 435,  -1,  -1])

In [201]:
# get the 20 random 2 digit numbers in 2D ndarray of shape 4, 5
a3 = np.random.randint(10, 100, 20).reshape((4, 5))

In [202]:
a3

array([[84, 33, 14, 60, 80],
       [54, 17, 99, 67, 30],
       [42, 61, 65, 14, 53],
       [21, 94, 20, 61, 36]])

In [203]:
a1

array([378, 480, 595,  -1,  -2, 490, 619, 908, 188, 545, 998, 675,   0,
        -1,  -1, 285, 932, 435,  -1,  -1])

In [204]:
# get the numbers GE 500 from a1
a1[ a1 >= 500 ]

array([595, 619, 908, 545, 998, 675, 932])

In [205]:
# get the negative numbers from a1
a1[a1 < 0]

array([-1, -2, -1, -1, -1, -1])

In [206]:
a3

array([[84, 33, 14, 60, 80],
       [54, 17, 99, 67, 30],
       [42, 61, 65, 14, 53],
       [21, 94, 20, 61, 36]])

In [207]:
# get the numbers GE 50 from a3
a3[ a3 >= 50 ]

array([84, 60, 80, 54, 99, 67, 61, 65, 53, 94, 61])

In [208]:
# get the numbers LE 80 from a3
a3[a3 <= 80]

array([33, 14, 60, 80, 54, 17, 67, 30, 42, 61, 65, 14, 53, 21, 20, 61, 36])

In [209]:
# get the numbers from a3 between 50 and 80
a3[ a3 >= 50 and a3 <= 80 ]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [210]:
a3 >= 50

array([[ True, False, False,  True,  True],
       [ True, False,  True,  True, False],
       [False,  True,  True, False,  True],
       [False,  True, False,  True, False]])

In [211]:
a3 <= 80

array([[False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [215]:
(a3 >= 50) & (a3 <= 80)

array([[False, False, False,  True,  True],
       [ True, False, False,  True, False],
       [False,  True,  True, False,  True],
       [False, False, False,  True, False]])

In [216]:
a3[ (a3 >= 50) & (a3 <= 80) ]

array([60, 80, 54, 67, 61, 65, 53, 61])

In [217]:
a3

array([[84, 33, 14, 60, 80],
       [54, 17, 99, 67, 30],
       [42, 61, 65, 14, 53],
       [21, 94, 20, 61, 36]])

In [218]:
# get the data which is LE 20 or GE 90
a3[ (a3 <= 20) | (a3 >= 90) ]

array([14, 17, 99, 14, 94, 20])

In [219]:
(a3 <= 20) 

array([[False, False,  True, False, False],
       [False,  True, False, False, False],
       [False, False, False,  True, False],
       [False, False,  True, False, False]])