In [5]:
t1 = (1, 2, 3, 4)

In [6]:
l1 = [10, 20, 30, 40, 50]

for var in l1:
    print(l1)

[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50]
[10, 20, 30, 40, 50]


In [7]:
d1 = { 1: 10, 2:20, 3:30 }

In [8]:
d1[2]

20

### sets

keyless dict

    - sets will store the unique data in the ordered form
    - values should be immutable type
    - sets can be used as iterables
    - we cant get the data out of set using index or key

In [9]:
s1 = { 1, 2, 4, 5, 4, 1 }

In [10]:
type(s1)

set

In [11]:
len(s1)

4

In [12]:
s1

{1, 2, 4, 5}

In [13]:
s2 = { 1, 2, 8, 4, 5, 6, 7, 8, 9, 1, 2, 3, 5, 1, 2, 4, 2, 1, 4, 3, 9}

In [14]:
s2

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [15]:
s3 = { t1 , 10, 10.5, 'text', True }

In [16]:
s3

{(1, 2, 3, 4), 10, 10.5, True, 'text'}

In [17]:
s1

{1, 2, 4, 5}

In [18]:
s1[2]

TypeError: 'set' object is not subscriptable

In [ ]:
for var in s1:
    print(var)

In [ ]:
print(dir(s1))

In [ ]:
s1.pop?

In [ ]:
s1

In [ ]:
s2

In [ ]:
s1.intersection( s2 )

In [ ]:
s2.difference( s1 )

In [ ]:
s1

In [ ]:
s2

In [ ]:
s2.difference_update( s1 )

In [ ]:
s2

In [ ]:
s1

In [ ]:
100 > 20

In [ ]:
'100' > '20'

### UDFs - USer Defined Functions

In [ ]:
sum([1, 2, 3, 4,5])

In [ ]:
sum([1, 2, 3, 4,'5'])

##### write a UDF to sum two numbers

In [ ]:
def sum_2_nums( n1, n2 ):
    return n1 + n2

In [ ]:
sum_2_nums( 10, 30 ) + 10

In [ ]:
sum_2_nums( '10', 30 )

##### write a UDF to subtract two numbers

In [ ]:
def sub2no( num1, num2 ):
    return num1 - num2

In [ ]:
sub2no( 20, 5 )

In [ ]:
sub2no( 5, 20 )

In [ ]:
sub2no( num1 = 20, num2 = 5 )

In [ ]:
sub2no( num2 = 20, num1 = 5 )

In [ ]:
sub2no( 20, num1 = 5 )

In [ ]:
sub2no( 20, num2 = 5 )

In [ ]:
sub2no( num1 = 20, 5 )

In [ ]:
def sub2no( num1 = 0, num2 = 0 ):
    return num1 - num2

In [ ]:
sub2no()

In [ ]:
sub2no( 10 )

In [ ]:
sub2no( num1 = 10 )

In [ ]:
sub2no( num2 = 10 )

In [19]:
sub2no(, 10)

SyntaxError: invalid syntax (<ipython-input-19-59eb79c144ee>, line 1)

In [ ]:
def sub2no( num1, num2 = 0 ):
    return num1 - num2

In [ ]:
sub2no()

In [ ]:
sub2no( 10 )

In [ ]:
sub2no( num2 = 10 )

In [ ]:
def sub2no( num1 = 0, num2 ):
    return num1 - num2

##### UDF to sum n numbers

In [ ]:
def sum_no( *args ):
    
    Sum = 0
    for var in args:
        if type(var) == int or type(var) == float:    # if type(var) in (int, float):
            Sum = Sum + var
    
    return Sum

In [ ]:
sum_no( 1, 2, 3, 4, '5', 10.5, True, (1, 2) )

In [ ]:
sum((1, 2, 3, 4, '5'))

### lambda functions

- they are defined with the keyword lambda; not def
- single line functions
- these functions will not have any name
- they will not be save in the memory

*Lambda functions are of NO use if used alone.* They are always uswed with some other functions

**In basic python, we use lambda functions with map(), filter()**

In [ ]:
# UDF to sum two numbers
def sum_2_no( a, b ):
    return a + b

In [ ]:
# lambda function to sum two numbers
lambda a, b: a + b

In [ ]:
l1 = list(range(1, 51, 10))

In [ ]:
l1

In [ ]:
# add no 10 to all the numbers in the list l1

In [ ]:
def func1( a ):
    return a + 10

In [ ]:
l2 = []
for var in l1:
    l2.append( func1( var ) )
    
l2

In [ ]:
list( map( func1, l1 ) )

In [ ]:
l3 = list( map( lambda var : var + 100, l1 ) )
l3

In [ ]:
l5 = [10, 20, 30, 40, 50, 60]

In [ ]:
l1

In [ ]:
l5

In [ ]:
list( map( lambda x, y: x + y, l1, l5 ))

In [ ]:
l1 = 5

In [ ]:
l6 = [1, 2, 3, 4, 3, 2,1 ,4 ,3 ,2 , 1, 4 , 5, 4]

In [ ]:
l6

In [ ]:
list(filter( lambda x: x % 2 != 0, l6 ))

## packages

In [ ]:
pip install numpy

### numpy

In [ ]:
import numpy as np

In [20]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

In [21]:
l1

[10, 20, 30, 40, 50]

In [22]:
type(l1)

list

In [24]:
a1 = np.array( l1 )

In [26]:
a1

array([10, 20, 30, 40, 50])

In [32]:
len(a1)

5

In [25]:
type(a1)

numpy.ndarray

In [35]:
a1.T

array([10, 20, 30, 40, 50])

In [37]:
a1

array([10, 20, 30, 40, 50])

In [36]:
a1.nbytes

20

In [38]:
a2 = np.array(l1, dtype = np.int8)

In [39]:
a2

array([10, 20, 30, 40, 50], dtype=int8)

In [40]:
a2.nbytes

5

In [42]:
a = input()

10


In [43]:
a

'10'

In [44]:
int(a)

10

In [49]:
var = input( 'Enter your marks:' )

float(var) / 100

Enter your marks:70


0.7

In [52]:
var = float(input( 'Enter your marks:' ))

Enter your marks:python


ValueError: could not convert string to float: 'python'

In [51]:
var

1.1